version: 1.0.{build}
os: Visual Studio 2015

install:
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
  - npm install npm@3.3.3 -g
  - set PATH=%APPDATA%\npm;%PATH%
  - npm --version

before_build:
  - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
  - ps: Vsix-IncrementNuspecVersion .\src\WebCompiler\MSBuild\*.nuspec
  - ps: Vsix-TokenReplacement src\WebCompilerVsix\WebCompilerPackage.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'
  - ps: Vsix-TokenReplacement src\WebCompiler\Compile\CompilerService.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'

build_script:
  - nuget restore -Verbosity quiet
  - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
  - ps: Vsix-PushArtifacts

artifacts:
  - path: src\WebCompiler\**\*.nupkg

deploy:
- provider: NuGet
  api_key:
    secure: 6xBu/05BWJDPa2PRkxEH3PHU/caLvy2lzf1eWdRBGXwSCTejHtI+6e0V4s2LaVri

after_deploy:
  - ps: Vsix-PublishToGallery .\src\WebCompilerVsix\**\*.vsix